//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inwestycje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sklepy
    {
        public int ID { get; set; }
        public string Lokal { get; set; }
        public string Miasto { get; set; }
        public string NazwaGalerii { get; set; }
        public double Metraz { get; set; }
        public string Brygadzista { get; set; }
    }
}
