//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inwestycje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int UserID { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Rola { get; set; }
    }
}
